baseURL = "https://jamtalk.netlify.com/"
languageCode = "en-us"
title = "Let's JAMstack!"
staticDir = [
    "static",
    "node_modules/reveal.js/js",
]

[params]
images = [
    "/img/jam/bball 2.gif"
]
